import Head from 'next/head'
import Image from 'next/image'
import gradient from "../public/gradient.jpg";
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.main__hero}>
          <Image 
              alt="Hero"
              src={gradient}  
          />
         
          <h1 className={styles.main__title}>
            Welcome!
          </h1>
        </div> 
        <div className={styles.main__grid}>
          <a href="/contatti"  className={styles.main__titBtn}>
            <h2 >Contattaci &rarr;</h2>
            <p>Hai necessità di ulteriori informazioni?</p>
          </a>


          
        </div>
      </main>

      
    </div>
  )
}
